#Add project

POST http://localhost:8000/api/add_project/
Content-Type: application/json

{
    "project_name": "Project 1",
    "user_id": "87279d92-0cdb-47e7-8c13-1fdf5f1214e6",
    "description": "Project 1 description",
    "target_amount": 1000,
    "start_date": "2019-01-01",
    "end_date": "2019-01-01"
}