# Generated by Django 5.0 on 2023-12-20 22:35

import crowd_funding.models.project
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_funding', '0002_alter_contribution_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_picture',
            field=models.ImageField(blank=True, default=crowd_funding.models.project.default_project_picture, upload_to=''),
        ),
    ]
