# Generated by Django 5.0 on 2023-12-21 16:11

import crowd_funding.models.project
import crowd_funding.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_funding', '0004_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(max_length=255, null=True, storage=crowd_funding.storage.UserProfileImageStorage(), upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_picture',
            field=models.ImageField(blank=True, default=crowd_funding.models.project.default_project_picture, storage=crowd_funding.storage.ProjectImageStorage(), upload_to='projects/'),
        ),
    ]
